<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-12-23 13:13
=======
# Generated by Django 4.1.2 on 2022-12-23 13:22
>>>>>>> 81dad2f3677efddf4f5c5140ed95df6ce01d3906

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=15)),
                ('image_URL', models.URLField()),
            ],
        ),
    ]
